x = [-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9];
x_tck = [-3,-2,-1,0,1,2,3,4];
y = [0,0,0,2,2,2,0,1,2,3,4,0,0,0,0,0];
subplot(1,2,1)
stem(x, y,'Color','k','MarkerFaceColor', 'k', 'MarkerEdgeColor', 'k', 'LineWidth', 3, 'BaseValue', 0);
ax = gca;
ax.XAxisLocation = 'origin';
ax.YAxisLocation = 'origin';
ax.XAxis.LineWidth = 2;
ax.YAxis.LineWidth = 2;
ax.XAxis.Color = 'k';
ax.YAxis.Color = 'k';
ax.XAxis.TickValues = x_tck;
ax.YAxis.TickValues = 4;
ax.XAxis.FontWeight = 'bold';
ax.YAxis.FontWeight = 'bold';
ax.XLabel.String = 'n';
ax.XLabel.FontName = 'italic';
ax.XLabel.FontSize = 10;
ax.XLabel.FontWeight = 'bold';
ax.YLabel.String = 'x(n)';
ax.YLabel.FontName = 'italic';
ax.YLabel.FontSize = 10;
ax.YLabel.FontWeight = 'bold';
ylim([-3, 7]);
xlim([-8, 11]);
box off;
subplot(1,2,2)
stem(x, y,'Color','k','MarkerFaceColor', 'k', 'MarkerEdgeColor', 'k', 'LineWidth', 3, 'BaseValue', 0);
ax = gca;
ax.XAxisLocation = 'origin';
ax.YAxisLocation = 'origin';
ax.XAxis.LineWidth = 2;
ax.YAxis.LineWidth = 2;
ax.XAxis.Color = 'k';
ax.YAxis.Color = 'k';
ax.XAxis.TickValues = x_tck;
ax.YAxis.TickValues = 4;
ax.XAxis.FontWeight = 'bold';
ax.YAxis.FontWeight = 'bold';
ax.XLabel.String = 'n';
ax.XLabel.FontName = 'italic';
ax.XLabel.FontSize = 10;
ax.XLabel.FontWeight = 'bold';
ax.YLabel.String = 'x(n)';
ax.YLabel.FontName = 'italic';
ax.YLabel.FontSize = 10;
ax.YLabel.FontWeight = 'bold';
ylim([-3, 7]);
xlim([-8, 11]);
box off;
